// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-F_XejGj-kDPz_3hAX2zVaL11RxwokY',
    appId: '1:880635326074:web:8fff15241e73b58e9b55c3',
    messagingSenderId: '880635326074',
    projectId: 'noteliness-6ede0',
    authDomain: 'noteliness-6ede0.firebaseapp.com',
    storageBucket: 'noteliness-6ede0.appspot.com',
    measurementId: 'G-F10VY5CTJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OxItJ0B7fRcpDQwRCzCG6Blo4MS74N4',
    appId: '1:880635326074:android:d071c794380fae8a9b55c3',
    messagingSenderId: '880635326074',
    projectId: 'noteliness-6ede0',
    storageBucket: 'noteliness-6ede0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_03iHw0Vy2CwhNUvEhac5STHpI0gJ_E',
    appId: '1:880635326074:ios:ec190cdc8592ba3a9b55c3',
    messagingSenderId: '880635326074',
    projectId: 'noteliness-6ede0',
    storageBucket: 'noteliness-6ede0.appspot.com',
    iosClientId: '880635326074-hcq05lfu509lmmu2srud08o0okaq7s8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteliness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_03iHw0Vy2CwhNUvEhac5STHpI0gJ_E',
    appId: '1:880635326074:ios:ec190cdc8592ba3a9b55c3',
    messagingSenderId: '880635326074',
    projectId: 'noteliness-6ede0',
    storageBucket: 'noteliness-6ede0.appspot.com',
    iosClientId: '880635326074-hcq05lfu509lmmu2srud08o0okaq7s8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteliness',
  );
}
