// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59O29VKLPF2yOePBqcMBAuoRPCHSD-Jk',
    appId: '1:357540309669:web:349781d85fc4e0a3757b4c',
    messagingSenderId: '357540309669',
    projectId: 'noteliness-7cbfd',
    authDomain: 'noteliness-7cbfd.firebaseapp.com',
    storageBucket: 'noteliness-7cbfd.appspot.com',
    measurementId: 'G-1NZZ2ECW6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lnVXlLS21GPkonI-QhVaBJX5y3DO5jY',
    appId: '1:357540309669:android:5325361f337131c4757b4c',
    messagingSenderId: '357540309669',
    projectId: 'noteliness-7cbfd',
    storageBucket: 'noteliness-7cbfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALy1n3M7rtfDOsrb02jBBKcvXXD6_p7C0',
    appId: '1:357540309669:ios:faf0848a5b85dc46757b4c',
    messagingSenderId: '357540309669',
    projectId: 'noteliness-7cbfd',
    storageBucket: 'noteliness-7cbfd.appspot.com',
    iosClientId: '357540309669-p53h351dhlimmvgjcrpo4o9ohvdbk56k.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteliness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALy1n3M7rtfDOsrb02jBBKcvXXD6_p7C0',
    appId: '1:357540309669:ios:faf0848a5b85dc46757b4c',
    messagingSenderId: '357540309669',
    projectId: 'noteliness-7cbfd',
    storageBucket: 'noteliness-7cbfd.appspot.com',
    iosClientId: '357540309669-p53h351dhlimmvgjcrpo4o9ohvdbk56k.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteliness',
  );
}
